In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import glob
import os

In [2]:
li = []

# Function to read and concatenate CSV files
def read_and_concatenate_files():
    global ds 
    path = '../../../CollectedData' # use your path
    all_files = glob.glob(os.path.join(path , "*.csv"))
    for filename in all_files:
        df = pd.read_csv(filename, index_col=None, header=0)
        li.append(df)
    ds = pd.concat(li, axis=0, ignore_index=True)
    ds.to_csv('test.csv', index=False)

In [3]:
read_and_concatenate_files()

In [7]:
global ds
df =ds
df

         Ticket #           Date Issue       Location Type  Hour      Day
0      24P0100001  2024-01-02 15:06:00     JOHNSON ST  101    15  Tuesday
1      24P0100002  2024-01-02 15:06:00     JOHNSON ST  TOW    15  Tuesday
2      24P0100003  2024-01-02 15:11:00     JOHNSON ST  101    15  Tuesday
3      24P0100004  2024-01-02 15:11:00     JOHNSON ST  TOW    15  Tuesday
4      24P0100005  2024-01-02 15:22:00     JOHNSON ST  101    15  Tuesday
...           ...                  ...            ...  ...   ...      ...
66396  24P3201772  2024-05-27 04:48:00       DARBO DR  063     4   Monday
66397  24P3201773  2024-05-27 04:48:00       DARBO DR  050     4   Monday
66398  24P3201774  2024-05-27 05:11:00  LAKE POINT DR  063     5   Monday
66399  24P3201775  2024-05-27 05:13:00  LAKE POINT DR  063     5   Monday
66400  24P3201776  2024-05-27 05:54:00  CREST LINE DR  081     5   Monday

[66401 rows x 6 columns]

In [8]:
colors = ["#0000e6", "#3b00f2", "#5b00fb", "#7e00fa", "#b500d1", "#d70075", "#e60000"]
ticket_type = "Parking"
days = 30

In [9]:
if (ticket_type is not None and "all" not in ticket_type):
        df = df[df['Type'].str.contains(ticket_type)]
df

         Ticket #           Date Issue    Location     Type  Hour        Day
497    24P0100498  2024-04-09 15:28:00  JOHNSON ST  Parking    15    Tuesday
498    24P0100499  2024-04-09 15:33:00  JOHNSON ST  Parking    15    Tuesday
1043   24P0200093  2024-01-10 13:19:00     MAIN ST  Parking    13  Wednesday
1044   24P0200094  2024-01-10 13:23:00     MAIN ST  Parking    13  Wednesday
1045   24P0200095  2024-01-10 13:28:00     MAIN ST  Parking    13  Wednesday
...           ...                  ...         ...      ...   ...        ...
56078  24P3000843  2024-02-02 06:06:00   TANCHO DR  Parking     6     Friday
64752  24P3200129  2024-01-23 12:05:00     MAIN ST  Parking    12    Tuesday
64753  24P3200130  2024-01-23 12:11:00     MAIN ST  Parking    12    Tuesday
64754  24P3200131  2024-01-23 12:15:00     MAIN ST  Parking    12    Tuesday
64755  24P3200132  2024-01-23 12:30:00     MAIN ST  Parking    12    Tuesday

[5505 rows x 6 columns]

In [10]:
df['Date Issue'].max()

'2024-05-28 15:41:00'

In [ ]:
import os
import glob
import pandas as pd
from datetime import datetime, timedelta

# Define the path to the directory containing the CSV files
path = r'C:\Users\marke\projects\parking\ParkingData\scr\CollectedData'  # Use your path

# Get a list of all CSV files in the directory
all_files = glob.glob(os.path.join(path, "*.csv"))

print(all_files)  # Print the list of files to verify

# Process each CSV file
for file in all_files:
    # Read the CSV file
    df = pd.read_csv(file, index_col=None, header=0)
    
    for row in df.iterrows():
        if row['Type'] == '05' or row['Type'] == '07':
            row['Type'] = "Parking"
        if row['Type'] == '09':
            row['Type'] = "Meter"
    
    # Save the processed data back to the CSV file
    df.to_csv(file, index=False)